apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: fullstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: alfinakash/fullstack-frontend:0.4
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: VITE_BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: VITE_BACKEND_URL
