apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: fullstack
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
  # Minikube → change type to NodePort
  # then run: minikube service frontend-service -n fullstack
