apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: fullstack
type: Opaque
data:
  DB_PASSWORD: YWRtaW4xMjM=                          
  JWT_SECRET: eW91cl9qd3Rfc2VjcmV0X2hlcmU=           
